version: '3'
services:

  db:
    image: postgres:15
    container_name: mtspostgres
    restart: always
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DATABASE}"]
      interval: 10s
      timeout: 20s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: employeeapi
    command: sh -c "python3 manage.py migrate --noinput --settings=employee_api.config.settings.dev && python manage.py runserver 0.0.0.0:8001 --settings=employee_api.config.settings.dev "
    restart: always
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    env_file:
      - .env
    depends_on:
      - db
          #condition: service_healthy


volumes:
  data:

networks:
  default:
    external:
      name: mtsnetwork